---
title: "Research"
output:
  distill::distill_article:
    toc: true
---


<style>
p {
  text-align: justify;
  

}
ul, li { margin: 0; padding: 0; }
</style>

# Publications


All my publications are available through my [CV](files/Julien_CV.pdf) or through [Google Scholar](https://scholar.google.fr/citations?user=TOQMW10AAAAJ&hl=fr).


# Dissertation

My [dissertation](https://tel.archives-ouvertes.fr/tel-03121350) examined how the digitalization of the real estate market enabled the financialization of housing,  thereby renewing patterns of social stratification and processes of urban segregation in Cape Town, South Africa.

Using in-depth fieldwork, spatial analysis and computational methods,I demonstrated how the housing market was reconfigured as a continuous flow of data through the adoption of digital platforms and the progressive making of housing as a financial asset, on both the buyer's and rental markets. In particular, the thesis highlighted how the adoption of credit scoring technologies and the spatial allocation of mortgages became critical market forces for the making of the middle class while driving neighborhood change in the post-apartheid city.

I use mixed methods combining qualitative and quantitative approaches. Over 18 months of fieldwork, I conducted interviews with market professionals and households, while engaged in participant-observation within a local estate agency in Khayelitsha, Cape Town's largest black township. In parallel, I built a database of 900,000 residential sales to measure and map the evolution of prices and mortgages across the urban space.

This thesis was awarded: 

- the 2021 [National Doctoral Prize in Urban Studies](http://www.urbanisme-puca.gouv.fr/prix-de-these-sur-la-ville-2021-a2141.html) by the PUCA-APERAU-Caisse des Dépôts.
- the 2021 [National Dissertation Award in Geography](https://www.cnfg.fr/vie-du-comite/prix-de-these-du-cnfg/) by the French National Committee of  Geography (CNFG).
- a Special mention of the jury for the 2021 [Humanities and social sciences PSL Dissertation Prize](https://psl.eu/en/news/winners-2021-humanities-and-social-sciences-shs-psl-dissertation-prize).



